# DO NOT DELETE

./tr.o: libowfat-0.32/stralloc.h /usr/include/unistd.h
./tr.o: /usr/include/features.h /usr/include/stdc-predef.h
./tr.o: /usr/include/regex.h /usr/include/fcntl.h /usr/include/stdio.h
./tr.o: /usr/include/errno.h /usr/include/stdlib.h /usr/include/alloca.h
./tr.o: /usr/include/string.h /usr/include/strings.h
