# DO NOT DELETE

tr.o: libowfat-0.32/stralloc.h /usr/include/unistd.h /usr/include/features.h
tr.o: /usr/include/stdc-predef.h /usr/include/regex.h /usr/include/fcntl.h
tr.o: /usr/include/stdio.h /usr/include/errno.h /usr/include/stdlib.h
tr.o: /usr/include/alloca.h /usr/include/string.h /usr/include/strings.h
