./aufgabe11.o: /usr/include/stdio.h /usr/include/_ansi.h
./aufgabe11.o: /usr/include/newlib.h /usr/include/_newlib_version.h
./aufgabe11.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
./aufgabe11.o: /usr/include/sys/features.h /usr/include/sys/cdefs.h
./aufgabe11.o: /usr/include/machine/_default_types.h /usr/include/sys/reent.h
./aufgabe11.o: /usr/include/sys/_types.h /usr/include/machine/_types.h
./aufgabe11.o: /usr/include/sys/lock.h /usr/include/sys/types.h
./aufgabe11.o: /usr/include/sys/_stdint.h /usr/include/machine/endian.h
./aufgabe11.o: /usr/include/machine/_endian.h /usr/include/bits/endian.h
./aufgabe11.o: /usr/include/sys/select.h /usr/include/sys/_sigset.h
./aufgabe11.o: /usr/include/sys/_timeval.h /usr/include/sys/timespec.h
./aufgabe11.o: /usr/include/sys/_timespec.h /usr/include/sys/_pthreadtypes.h
./aufgabe11.o: /usr/include/machine/types.h /usr/include/endian.h
./aufgabe11.o: /usr/include/bits/byteswap.h /usr/include/bits/wordsize.h
./aufgabe11.o: /usr/include/sys/sysmacros.h /usr/include/sys/stdio.h
./aufgabe11.o: ./libowfat-0.32/stralloc.h /usr/include/math.h
./aufgabe11.o: /usr/include/limits.h /usr/include/features.h
./aufgabe11.o: /usr/include/string.h /usr/include/xlocale.h
./aufgabe11.o: /usr/include/strings.h /usr/include/sys/string.h
./aufgabe11.o: /usr/include/stdlib.h /usr/include/machine/stdlib.h
./aufgabe11.o: /usr/include/alloca.h
# DO NOT DELETE

binaer.o: /usr/include/stdio.h /usr/include/_ansi.h /usr/include/newlib.h
binaer.o: /usr/include/_newlib_version.h /usr/include/sys/config.h
binaer.o: /usr/include/machine/ieeefp.h /usr/include/sys/features.h
binaer.o: /usr/include/sys/cdefs.h /usr/include/machine/_default_types.h
binaer.o: /usr/include/sys/reent.h /usr/include/sys/_types.h
binaer.o: /usr/include/machine/_types.h /usr/include/sys/lock.h
binaer.o: /usr/include/sys/types.h /usr/include/sys/_stdint.h
binaer.o: /usr/include/machine/endian.h /usr/include/machine/_endian.h
binaer.o: /usr/include/bits/endian.h /usr/include/sys/select.h
binaer.o: /usr/include/sys/_sigset.h /usr/include/sys/_timeval.h
binaer.o: /usr/include/sys/timespec.h /usr/include/sys/_timespec.h
binaer.o: /usr/include/sys/_pthreadtypes.h /usr/include/machine/types.h
binaer.o: /usr/include/endian.h /usr/include/bits/byteswap.h
binaer.o: /usr/include/bits/wordsize.h /usr/include/sys/sysmacros.h
binaer.o: /usr/include/sys/stdio.h
